Mellanox/ngc_multinode_perf

ngc_tcp_test.sh

Tested over AMD system with 100GbE NIC.
Used `AMDuProfPcm -m memory -a -d 10` to verify the socket memory bandwidth is as expected.
Here is the output for socket 1 memory bandwidth:
| Umc0RdWrBw (GB/s) | Umc1RdWrBw (GB/s) | Umc2RdWrBw (GB/s) | Umc3RdWrBw (GB/s) | Umc4RdWrBw (GB/s) | Umc5RdWrBw (GB/s) | Umc6RdWrBw (GB/s) | Umc7RdWrBw (GB/s) | Umc0RdWrBw (GB/s) | Umc1RdWrBw (GB/s) | Umc2RdWrBw (GB/s) | Umc3RdWrBw (GB/s) | Umc4RdWrBw (GB/s) | Umc5RdWrBw (GB/s) | Umc6RdWrBw (GB/s) | Umc7RdWrBw (GB/s) |
|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|--------------- …

Change IRQ allocation to Socket CPUs

---

ngc_tcp_test.sh

* Support running from VM where device NUMA node is "-1"
* Bidirectional support
* Option to keep MTU as previously configured
* Print iperf3 version and linux boot parameters
* Fix running on CPUs with less than 16 cores
* Choose TCP base port randomly so it will not be in established state next time
* Fix irq affinity on server using the client cores

ngc v2.2 performance and connectivity bugs

---

README.md
common.sh
ipsec_configuration.sh
ngc_ipsec_crypto_offload_tcp_test.sh
ngc_tcp_test.sh

add IPsec crypto offload test
refactor common functions and IPsec common functions to separate files
Signed-off-by: Dor Kovacsi <dorko@nvidia.com>

IPsec crypto offload test capability

---

README.md
common.sh
ipsec_configuration.sh
ipsec_full_offload_setup.sh
mlnx_tune
ngc_ipsec_crypto_offload_tcp_test.sh
ngc_ipsec_full_offload_tcp_test.sh
ngc_rdma_test.sh
ngc_tcp_test.sh
run_iperf3_clients.sh
run_iperf3_servers.sh

This PR brings multiple enhancements and new features. For full details please see the individual commit messages, but here are the main ones:
* Allow runs for non-root users (provided a passwordless access to the servers, and a passwordless `sudo` access to **some** executables).
* Preparation for multi-port support for IPsec full offload - for now at the config stage only.
* Fix a bug preventing runs from a controller machine which is not one of the machines under test.
* Print the theoretical port rate near the actual result, for comparison.
* Flush IPsec settings on the DPU in the end of every IPsec full offload run - this improves the stability of the system.
* Many stability, efficiency, style, and documentation fixes.

Multiple enhancements and new features

---

ngc_rdma_test.sh
ngc_rdma_wrapper.sh

Added external loopback function
Added ssh connectivtiy test function
Added results function

Add external loopback

---

ngc_rdma_test.sh
ngc_rdma_wrapper.sh

Add mlx devices when echoing results

Add devices for results

---

ngc_rdma_wrapper.sh

-Add Server SN for Hiper servers to log file

Add Serial Number (Hiper Servers)

---

ngc_rdma_wrapper.sh

Add BIOS version

---

ngc_rdma_wrapper.sh

Refactor Hiper -> ISR1

---

ngc_rdma_wrapper.sh

Remove ISR1 function and refactor it as external loopback function.

Remove ISR1 function

---

README.md
common.sh
ngc_tcp_test.sh

Please see the individual commit messages for details.

Make the TCP iperf3 test work between DPUs + minor refactoring

---

ngc_rdma_test.sh

Please see the individual commit messages for details.

Fix variable handling.

---

common.sh
ngc_tcp_test.sh

Please the the individual commit messages for details.

Critical, efficiency, and syntax fixes

---

README.md

README: Avoid long lines for better visibility

---

common.sh
ngc_tcp_test.sh

Please see the individual commit messages for details.

Some functionality and cosmetic fixes

---

ngc_rdma_wrapper.sh

Just a minor change in text output

STDOUT change

---

ngc_internal_lb_rdma_wrapper.sh
ngc_rdma_wrapper.sh

- Align ngc_rdma_wrapper to the internal_lb wrapper
- Some cosmetic changes to internal_lb wrapper

ngc_rdma_wrapper changes

---

README.md
common.sh
ipsec_full_offload_setup.sh
ngc_rdma_test.sh

- Adding support for multiple ports.
- Adding support for multiple devices.

RDMA: Add IPsec full-offload support

---

common.sh

common: Fix get_cores_for_devices function

---

README.md
common.sh
ngc_tcp_test.sh

Additional Changes:
- Updated pass criteria for IPsec.
- Modified Collect_BW function to end with return instead of exit.

ngc_tcp_test: Implement IPsec full offload support

---

common.sh

Fix the json file name in the SD func.

ngc_rdma_test: Fix SD json naming

---

ngc_rdma_test.sh

rdma: Fit actual arguments to documented ones

---

common.sh
ngc_rdma_test.sh

Allows a list of CUDA devices to be used in a single run

NGC RDMA test: Support list of CUDA devices

---

README.md
common.sh
ngc_rdma_test.sh

Description: use_null_mr, post_list
Issue:
DependentChanges:
Reviewed By:
Bug exists in prev GA <delete if NA>

NGC_RDMA_TEST: Add perftest flags
